name: Sync

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions: write-all

jobs:
    SyncData:
        runs-on: ubuntu-latest
        env:
            PYTHONIOENCODING: utf-8
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy:
            fail-fast: true
        steps:
        - uses: actions/checkout@v4
        - uses: FedericoCarboni/setup-ffmpeg@v3
        - uses: peaceiris/actions-mdbook@v2
          with:
                mdbook-version: 'latest'
        - run: pip install --upgrade pip
        - run: pip install -r requirements.txt
        - run: sudo apt install libogg-dev libvorbis-dev -y
        - run: python main.py
        - run: python upload.py
        - run: python mdbook.py
        - run: mdbook build
        - uses: stefanzweifel/git-auto-commit-action@v5
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v5
        - uses: actions/upload-pages-artifact@v3
          with:
                path: ./book
    deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: SyncData
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4