name: Sync

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions: write-all

jobs:
    Sync_Data:
        runs-on: ubuntu-latest
        env:
            PYTHONIOENCODING: utf-8
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy:
            fail-fast: true
        steps:
        - uses: actions/checkout@v4
        - uses: FedericoCarboni/setup-ffmpeg@v3
        - uses: peaceiris/actions-mdbook@v2
          with:
                mdbook-version: 'latest'
        - run: pip install --upgrade pip
        - run: pip install -r requirements.txt
        - run: sudo apt install libogg-dev libvorbis-dev -y
        - run: python main.py
        - run: python upload.py
        - run: python mdbook.py
        - run: mdbook build
        - uses: stefanzweifel/git-auto-commit-action@v5
        - uses: peaceiris/actions-gh-pages@v4
          with:
            publish_dir: ./book